---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: userspace-cni
  namespace: openshift-multus
spec:
  selector:
    matchLabels:
      app: userspace-cni
  template:
    metadata:
      labels:
        app: userspace-cni
    spec:
      containers:
      - name: userspace-cni-plugin
        image: localhost:5000/userspacecni #registory:imagename
        imagePullPolicy: Always
        securityContext:
           allowPrivilegeEscalation: false
           privileged: false
        resources:
          requests:
             cpu: 1m
             memory: 1Mi
          limits:
             cpu: 100m
             memory: 30Mi
        volumeMounts:
        - name: cnibin
          mountPath: /var/lib/cni/bin/
        command: ["/bin/sh","-c"]
        args: ["cp -rf /root/userspace-cni-network-plugin/userspace/userspace /var/lib/cni/bin; sleep inf"]
      volumes:
        - name: cnibin
          hostPath:
            path: /var/lib/cni/bin/
